### ISSUE TITLE
implementation 'com.github.erenalpaslan:removebg:1.0.4'

### ISSUE THREAD

**Issue by brunoalex** [erenalpaslan/removebg#11]
this wont work implementation 'com.github.erenalpaslan:removebg:1.0.4' help ?

**Comment by erenalpaslan** [comment]
I am able to implement the library with given example did you follow instructions correctly.

**Comment by brunoalex** [comment]
i think so, im getting 

Failed to resolve: com.github.erenalpaslan:removebg:1.0.4
Show in Project Structure dialog
Affected Modules: app

![image](https://github.com/AppcentMobile/removebg/assets/15779919/0f731d6f-e8de-4cf7-b61f-59eace12c2d8)


seams like a cant download ...

**Comment by erenalpaslan** [comment]
Can you try to add the below line to your project level gradle you need to define jitpack.io as a repository after that gradle will try to download it from jitpack
```
allprojects {
    repositories {
      ...
      maven { url 'https://jitpack.io' }
    }
}

**Comment by brunoalex** [comment]
Your right ..tryed that again and it works tks erenalpaslan,
