### ISSUE TITLE
big size 

### ISSUE THREAD

**Issue by brunoalex** [erenalpaslan/removebg#12]
i see that you use libpytorch_jni_lite.so 50mb this is huge... any ideia on how to reduce the size? tks ..great lib:) 
maybe : 

Use selective build to only include the used operators in the final library, see

[https://pytorch.org/tutorials/recipes/mobile_interpreter.html#how-to-use-mobile-interpreter-custom-build 43](https://pytorch.org/tutorials/recipes/mobile_interpreter.html#how-to-use-mobile-interpreter-custom-build)
and
[(prototype) Tracing-based Selective Build Mobile Interpreter in Android and iOS — PyTorch Tutorials 1.12.0+cu102 documentation 31](https://pytorch.org/tutorials/prototype/tracing_based_selective_build.html) (even smaller size)

**Comment by erenalpaslan** [comment]
I will check it but pytorch lib is main component in this project.
Did you use app bundle or apk

**Comment by brunoalex** [comment]
im using bundle

**Comment by brunoalex** [comment]
bundle reduces the files to 20mb on delivery it fine ... my mistake tks
