### ISSUE TITLE
How do you converted u2net .pth model converted to a .ptl model？

### ISSUE THREAD

**Issue by YueDev** [erenalpaslan/removebg#15]
i followed the instructions on https://pytorch.org/mobile/home/ to do it, but it didn't work. Could you please describe how you converted it?

**Comment by YueDev** [comment]
I found a way to do this, it seems good.
~~~
import torch
from u2net import U2NETP
from torch.utils.mobile_optimizer import optimize_for_mobile

path = "./model/u2netp.pth"
ptl_path = "./model/u2netp.ptl"

model = U2NETP(3, 1)
weights = torch.load(path, map_location='cpu')
model.load_state_dict(weights)
device = torch.device('cpu')
model.to(device)
model.eval()

scripted_model = torch.jit.script(model)
opt_model = optimize_for_mobile(scripted_model)
opt_model._save_for_lite_interpreter(ptl_path)

~~~

**Comment by erenalpaslan** [comment]
actually as i remember i got a .ptl from drive links that included at the bottom in this repository [u2net](https://github.com/xuebinqin/U-2-Net)

**Comment by anonym24** [comment]
> I found a way to do this, it seems good.
> from u2net import U2NETP
> ```

Hi. 

Can you please explain does where U2NETP come from?
