### ISSUE TITLE
Not good results sometimes

### ISSUE THREAD

**Issue by Shadkirill** [erenalpaslan/removebg#9]
Hi!
I tested your library. It works really well and fast.
but results sometimes are not as good as in other services which are also based on the same ML model.
Do you have any ideas how to improve?
maybe use another dataset for training?
If you want me to give example of service which works better, u can try to run model on replicate https://replicate.com/cjwbw/rembg/versions/fb8af171cfa1616ddcf1242c093f9c46bcada5ad4cf6f2fbe8b81b330ec5c003
it is also based on u2net

Best, Kyrylo.

**Comment by erenalpaslan** [comment]
Hi @Shadkirill,

Sorry for my late answer. On `Removebg` i used U2NetP which has less feature maps than the U2Net model so this kind of problems can be related with these. U2NetP has very small size (round 4.7 MB) and when we put it into our app directly (not getting model from a holder, server etc.) it wont increase our app size too much. Actual U2Net size is 176 MB.

You can check: [https://medium.com/appcent/image-segmentation-in-android-80ba75ffa5e9]( https://medium.com/appcent/image-segmentation-in-android-80ba75ffa5e9)

** Actually i don't have any other implementation so i don't give you some other example or service but there are more efficient ways

For improving the model efficiency in my thoughts:
- Using U2Net or any other pre-trained model in backend service so app size can be still small.
- Using ML Kit's Subject Segmentation can be good at for removing background apps.

Regards,
